export const products = [
    {
        name: "All Saints round Logo",
        category: "tshirt",
        price: 85,
        description: "t-shirt All Saints black round logo white",
        stock: 100,
        brand: "all saints",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712616744/t_shirt_all_saints_round_black_ybtphb.avif",
    },
    {
        name: "Drew letters Logo ",
        category: "tshirt",
        price: 65,
        description: "t-shirt drew oversized typography Drew",
        stock: 100,
        brand: "drew",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712618394/t_shirt_drew_kzeid1.webp",
    },
    {
        name: "Drew logo smile",
        category: "tshirt",
        price: 65,
        description: "t-shirt Drew white smile face logo",
        stock: 100,
        brand: "drew",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712616992/drew_smile_face_logo_white_jndcj6.webp",
    },
    {
        name: "Essential",
        category: "tshirt",
        price: 70,
        description: "t-shirt essential fear of god oversize black color",
        stock: 100,
        brand: "Essential",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712608813/t_shirt_essential_black_ngkv2z.webp",
    },
    {
        name: "Essential",
        category: "tshirt",
        price: 70,
        description: "t-shirt essential fear of god oversize cream color",
        stock: 100,
        brand: "Essential",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712608251/t_shirt_essential_cream_qootjc.webp",
    },
    {
        name: "Essential Hoodie",
        category: "hoodie",
        price: 140,
        description: "hoodie essential small logo 'Fear Of God'",
        stock: 100,
        brand: "Essential",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712608816/hoodie_essential_black_a8szev.webp",
    },
    {
        name: "Drew hoodie",
        category: "hoodie",
        price: 150,
        description: "hoodie drew cream color smile logo oversize",
        stock: 100,
        brand: "drew",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712880890/hoodie_drew_cream_smile_logo_hd01dg.webp",
    },
    {
        name: "Drew hoodie",
        category: "hoodie",
        price: 150,
        description: "hoodie drew black color 'DREW' logo",
        stock: 100,
        brand: "drew",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712880707/hoodie_drew_logo_black_x14hhg.webp",
    },
    {
        name: "Off-white hoodie",
        category: "hoodie",
        price: 90,
        description: "hoodie off-white white black logo sleves",
        stock: 100,
        brand: "off white",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712880708/hoodie_offwhite_white_qosxwj.webp",
    },
    {
        name: "RamitheIcon hoodie ",
        category: "hoodie",
        price: 50,
        description: "Ramitheicon hoodie black 'ICON' logo ",
        stock: 100,
        brand: "ramitheicon",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712880707/hoodie_ramitheicon_Icon_logo_black_j178sz.webp",
    },
    {
        name: "Essential sweetpants ",
        category: "pants",
        price: 60,
        description: "light oatmeal essential pants",
        stock: 70,
        brand: "essential",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712984213/pants_essential_light_oatmeal_a7azyz.avif",
    },
    {
        name: "Essential sweetpants ",
        category: "pants",
        price: 60,
        description: "black essential pants",
        stock: 100,
        brand: "essential",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712984278/pants_essential_black_olshjz.webp",
    },
    {
        name: "Original Jeans",
        category: "pants",
        price: 120,
        description: "Original black jeans customs oversize",
        stock: 100,
        brand: "original",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712982659/pants_custom_jeans_bkack_cnft7y.jpg",
    },
    {
        name: "Original Sponge",
        category: "pants",
        price: 130,
        description: "Original blue jeans custom SpongeBob",
        stock: 100,
        brand: "original",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712982655/pants_jean_custom_sponge_bob_wigrrd.jpg",
    },
    {
        name: "Pacsun cargo",
        category: "pants",
        price: 40,
        description: "Slim cargo pants cream",
        stock: 100,
        brand: "pacsun",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712982796/pants_cargo_slimfit_cream_ehcgm0.webp",
    },
    {
        name: "Pacsun cargo",
        category: "pants",
        price: 40,
        description: "Slim cargo pants camel",
        stock: 100,
        brand: "pacsun",
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712982751/pants_cargo_relaxe_fit_camel_ov7ych.webp",
    },
]
