export const products = [
    {
        id: "1",
        name: "All Saints",
        category: "tshirt",
        price: 95,
        description: "t-shirt All Saints Black",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712616812/t_shirt_all_saints_black_c03szm.avif",
    },
    {
        id: "2",
        name: "All Saints round Logo",
        category: "tshirt",
        price: 85,
        description: "t-shirt All Saints round Logo Black",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712616744/t_shirt_all_saints_round_black_ybtphb.avif",
    },
    {
        id: "3",
        name: "Drew",
        category: "tshirt",
        price: 65,
        description: "t-shirt drew oversized blue",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712618394/t_shirt_drew_kzeid1.webp",
    },
    {
        id: "4",
        name: "Drew smile",
        category: "tshirt",
        price: 65,
        description: "t-shirt Drew smile logo white",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712616992/drew_smile_face_logo_white_jndcj6.webp",
    },
    {
        id: "5",
        name: "Essential fear of god",
        category: "tshirt",
        price: 70,
        description: "t-shirt essential fear of god black",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712608813/t_shirt_essential_black_ngkv2z.webp",
    },
    {
        id: "6",
        name: "Essential fear of god",
        category: "tshirt",
        price: 60,
        description: "t-shirt essential fear of god cream",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712608251/t_shirt_essential_cream_qootjc.webp",
    },
    {
        id: "7",
        name: "Essential Hoodie fear of god",
        category: "hoodie",
        price: 140,
        description: "hoodie essential fear of god",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712608816/hoodie_essential_fear_of_god_black_yisjdk.webp",
    },
    {
        id: "8",
        name: "Hoodie essential pocket Logo",
        category: "hoodie",
        price: 140,
        description: "hoodie essential fear of god",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712608816/hoodie_essential_black_a8szev.webp",
    },
    {
        id: "9",
        name: "Hoodie drew cream",
        category: "hoodie",
        price: 150,
        description: "hoodie drew cream smile logo",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712880890/hoodie_drew_cream_smile_logo_hd01dg.webp",
    },
    {
        id: "10",
        name: "Hoodie drew black",
        category: "hoodie",
        price: 150,
        description: "hoodie logo drew black",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712880707/hoodie_drew_logo_black_x14hhg.webp",
    },
    {
        id: "11",
        name: "Hoodie Off-White",
        category: "hoodie",
        price: 90,
        description: "hoodie off-white white",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712880708/hoodie_offwhite_white_qosxwj.webp",
    },
    {
        id: "12",
        name: "Hoodie RamitheIcon",
        category: "hoodie",
        price: 50,
        description: "hoodie rami the icon black",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712880707/hoodie_ramitheicon_Icon_logo_black_j178sz.webp",
    },
    {
        id: "13",
        name: "Sweetpants Essential",
        category: "pants",
        price: 60,
        description: "light oatmeal essential pants",
        stock: 70,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712984213/pants_essential_light_oatmeal_a7azyz.avif",
    },
    {
        id: "14",
        name: "Sweetpants Essential",
        category: "pants",
        price: 60,
        description: "black essential pants",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712984278/pants_essential_black_olshjz.webp",
    },
    {
        id: "15",
        name: "Black jeans custom",
        category: "pants",
        price: 120,
        description: "Black jeans custom oversize",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712982659/pants_custom_jeans_bkack_cnft7y.jpg",
    },
    {
        id: "16",
        name: "Sponge bob Jeans",
        category: "pants",
        price: 130,
        description: "Blue jeans custom Sponge bob",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712982655/pants_jean_custom_sponge_bob_wigrrd.jpg",
    },
    {
        id: "17",
        name: "Cargo pants",
        category: "pants",
        price: 40,
        description: "Slim cargo pants cream",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712982796/pants_cargo_slimfit_cream_ehcgm0.webp",
    },
    {
        id: "18",
        name: "Cargo pants camel",
        category: "pants",
        price: 40,
        description: "Slim cargo pants camel",
        stock: 100,
        img: "https://res.cloudinary.com/dzvzm9qcl/image/upload/v1712982751/pants_cargo_relaxe_fit_camel_ov7ych.webp",
    },
]
